"""Cumulative CYS403 practice exams, built by scripts/build_cys403_study_tools.py.

Scopes follow the syllabus: Quiz 1 covers Chapters 1–2; the Major exam (week 8) covers
Chapters 1–6. Questions here are new, not copies of the chapter quizzes.
"""

QUIZ_1 = {
    "mcq": [
        ("Which pair of frameworks does Risk IT complement and extend?",
         ["ISO 27001 and NIST CSF", "COBIT and Val IT", "ITIL and Common Criteria", "OCTAVE and PASTA"], 1, "Risk IT complements and extends COBIT and Val IT.", "Ch1 · Frameworks"),
        ("A board of directors approves the organization's long-range security policy. This is which level of planning?",
         ["Operational", "Tactical", "Strategic", "Procedural"], 2, "Strategic planning is long term and high level, e.g. the overall security policy.", "Ch1 · Planning"),
        ("Which element turns functional policies into enforceable actions by specifying the minimum security configuration for a platform?",
         ["Guideline", "Baseline", "Security statement", "Blueprint"], 1, "Baselines ensure a minimum, platform-unique security configuration.", "Ch1 · Implementation"),
        ("Which requirement type is selected based on the risk management process and defines the security behavior of a control?",
         ["Assurance requirement", "Functional requirement", "Business requirement", "Legal requirement"], 1, "Functional requirements define security behavior and are chosen through risk management.", "Ch1 · Security solutions"),
        ("A disgruntled former employee who could harm the company, but has not yet acted, is best described as a:",
         ["Threat agent", "Attacker", "Residual risk", "Exposure"], 0, "A threat agent has the potential to cause a threat; an attacker is the actual cause of an attack.", "Ch2 · Terms"),
        ("Which risk management step uses the Risk Register to monitor, track and review risks?",
         ["Step 2", "Step 3", "Step 4", "Step 5"], 3, "Step 5, monitor and review, uses the Risk Register.", "Ch2 · Steps"),
        ("In the AS/NZS 4360 matrix, a 'rare' (E) likelihood with an 'insignificant' (1) consequence is:",
         ["Low", "Moderate", "High", "Extreme"], 0, "Row E, column 1 is L: routine acceptance.", "Ch2 · Qualitative"),
        ("A company stops offering an online service because its risk is too high. Which mitigation option is this?",
         ["Acceptance", "Reduction", "Transference", "Avoidance"], 3, "Stopping the activity that creates the risk is avoidance.", "Ch2 · Mitigation"),
        ("Restoring data from backup after a ransomware incident is an example of which control type?",
         ["Directive", "Detective", "Recovery", "Preventive"], 2, "Recovery controls restore systems to normal operation.", "Ch2 · Controls"),
        ("Which countermeasure selection principle requires that a safeguard can be tested and audited?",
         ["Sustainability", "Audit capability", "Universal application", "Vendor trustworthiness"], 1, "Audit capability means the safeguard can be tested and audited.", "Ch2 · Selection"),
    ],
    "tf": [
        ("Val IT provides an end-to-end view of all IT-related risks.", False, "That describes Risk IT. Val IT creates business value from IT investments.", "Ch1 · Frameworks"),
        ("Cybersecurity management includes governance and risk management.", True, "Both are listed as parts of cybersecurity management.", "Ch1 · Management"),
        ("Procedures are recommendations that employees may choose to follow.", False, "Procedures are step-by-step actions that must be followed; guidelines are recommendations.", "Ch1 · Implementation"),
        ("Risk management should identify potential risks before they occur and across the life of the project.", True, "That is the stated purpose of risk management.", "Ch2 · Purpose"),
        ("Qualitative risk analysis assigns absolute monetary values to all risk components.", False, "Qualitative analysis does not assign absolute numeric values; quantitative does.", "Ch2 · Qualitative"),
        ("Corrective controls react to a detected incident to reduce the chance of it recurring.", True, "That is the definition of corrective controls.", "Ch2 · Controls"),
    ],
    "fill": [
        ("The three properties protected by cybersecurity are confidentiality, integrity and ________.", "availability", ["availability"], "CIA triad.", "Ch1 · CIA"),
        ("Policies gain credibility through top ________ buy-in.", "management", ["management"], "Top management buy-in gives policies credibility.", "Ch1 · Policy"),
        ("Risk remaining after countermeasures are applied is ________ risk.", "residual", ["residual"], "Residual risk.", "Ch2 · Terms"),
        ("The Delphi technique and bow-tie analysis are ________ risk analysis techniques.", "qualitative", ["qualitative"], "Both are among the five top qualitative techniques.", "Ch2 · Qualitative"),
    ],
    "calc": [
        ("An asset worth $20,000 has an exposure factor of 25%. What is the SLE?", "5,000", ["5000", "5,000"], "SLE = 20,000 × 0.25 = 5,000.", "Ch2 · Quantitative"),
        ("SLE = $5,000 and the threat occurs 6 times a year. What is the ALE?", "30,000", ["30000", "30,000"], "ALE = 5,000 × 6 = 30,000.", "Ch2 · Quantitative"),
        ("ALE before = $30,000, ALE after = $10,000, annual control cost = $12,000. What is the value of the control?", "8,000", ["8000", "8,000"], "30,000 − 10,000 − 12,000 = 8,000, so the control is worth buying.", "Ch2 · Quantitative"),
    ],
    "match": [
        ("Match each term from Chapters 1–2 to its definition.", "Ch1–2 · Terms", [
            ("COBIT", "IT governance model for delivering value and managing IT risk"),
            ("Security blueprint", "Structure for organizing requirements and solutions"),
            ("Attack", "Any actual danger to information or systems"),
            ("Exposure", "Opportunity for a threat to cause loss"),
            ("Risk transference", "Passing risk to a third party"),
        ]),
    ],
    "short": [
        ("Explain the difference between standards, procedures, guidelines and baselines, with one example of each.",
         ["standard", "procedure", "guideline", "baseline", "minimum", "step"],
         "Standards adopt common hardware and software mechanisms enterprise-wide (e.g. one approved anti-virus). Procedures are step-by-step actions that must be followed (e.g. how to reset a password). Guidelines are recommendations for implementation and planning (e.g. ISO 17799, ITIL). Baselines are benchmarks setting a minimum, platform-unique security configuration (e.g. password rules, VPN setup).",
         "Ch1 · Implementation"),
        ("Scenario: A hospital's patient records server faces ransomware. Describe how the five types of security controls could each be applied.",
         ["directive", "preventive", "detective", "corrective", "recovery", "backup"],
         "Directive: an acceptable-use policy and awareness training telling staff not to open suspicious attachments. Preventive: email filtering, patching, and access controls. Detective: an IDS or anti-malware alerts that spot encryption activity. Corrective: isolating infected machines and removing the malware so it doesn't recur. Recovery: restoring patient records from clean backups to return to normal operations.",
         "Ch2 · Controls"),
    ],
}

MAJOR = {
    "mcq": [
        ("According to Chapter 1, cybersecurity governance must be fully integrated into:",
         ["The marketing plan", "Overall risk analysis and management", "The firewall configuration", "Vendor contracts only"], 1, "Governance is fully integrated into overall risk analysis/management.", "Ch1 · Governance"),
        ("Which is an example of a functional policy?",
         ["Remote access policy", "Firewall product standard", "VPN baseline", "ITIL guideline"], 0, "Remote access is one of the functional policies listed.", "Ch1 · Policy"),
        ("The formula 'Value of control = ALE(before) − ALE(after) − ACS' is used to:",
         ["Compute SLE", "Decide whether a control is cost-justified", "Rank DREAD scores", "Classify assets"], 1, "A positive value means the control saves more than it costs.", "Ch2 · Quantitative"),
        ("Which qualitative technique is known as a 'Structured What-If'?",
         ["Delphi", "SWIFT", "Bow-tie", "Decision tree"], 1, "SWIFT = Structured What-If Technique.", "Ch2 · Qualitative"),
        ("Using a stolen session ID cookie to access someone else's session is:",
         ["Session hijacking", "Hidden-field tampering", "Port scanning", "Privilege elevation"], 0, "Session hijacking uses a stolen session ID.", "Ch3 · Application threats"),
        ("Which threat modeling method combines attack trees, STRIDE and CVSS?",
         ["hTMM", "Quantitative TMM", "Trike", "OCTAVE"], 1, "Quantitative TMM applies attack trees, STRIDE, and CVSS in synergy.", "Ch3 · Threat modeling"),
        ("In LINDDUN, being able to identify the sender of an email within a group is:",
         ["Linkability", "Identifiability", "Detectability", "Unawareness"], 1, "Identifiability is identifying the subject within a set of subjects.", "Ch3 · LINDDUN"),
        ("Which Chapter 4 community of interest is responsible for building and maintaining secure systems?",
         ["Cyber security", "Information technology", "Management", "Users"], 1, "IT builds and maintains secure systems.", "Ch4 · Accountability"),
        ("A worksheet listing assets by priority on one axis and threats by priority on the other, recording vulnerabilities in the cells, is the:",
         ["Risk register", "POAM", "TVA worksheet", "Ranked risk worksheet"], 2, "The Threat–Vulnerability–Asset worksheet combines both prioritized lists.", "Ch4 · TVA"),
        ("Which asset attribute is tracked for procedures?",
         ["IP address", "Where it is stored for update purposes", "Security clearance", "Serial number"], 1, "Procedure attributes include description, purpose, related elements, and storage locations for reference and update.", "Ch4 · Inventory"),
        ("A qualitative risk assessment is described as:",
         ["Objective and data heavy", "Subjective and based on expert opinion", "Purely mathematical", "Impossible to complete quickly"], 1, "Qualitative RA is subjective and relies on experts; it is quick.", "Ch5 · Methods"),
        ("In the risk determination formula, if data is 70% accurate, the uncertainty used is:",
         ["70%", "30%", "7%", "0%"], 1, "Uncertainty = 1 − 0.7 = 30%.", "Ch5 · Risk determination"),
        ("A web server's critical area in the RA scope example was:",
         ["Inspection of all traffic", "Single point of failure and OS patch status", "Only data exchanged with the database", "Backup tapes"], 1,
         "Web server: SPOF and OS updates; database: exchanged data; firewall: traffic inspection.", "Ch5 · Components"),
        ("During RA preparation, which information comes from reviewing the current status of ACCEPTED recommendations?",
         ["The organization's receptiveness to rejected controls", "The effectiveness of recommendations in place and justification for those not in place", "The system mission", "IP addresses in use"], 1,
         "Accepted recommendations show effectiveness (in place) and justification (not in place).", "Ch6 · Review"),
        ("Which is the correct order of the last four steps of the RA plan?",
         ["Evaluate risks, assess exploits, present, recommend", "Assess threats/vulnerabilities/exploits, evaluate risks, develop recommendations, present to management",
          "Present, recommend, evaluate, assess", "Identify countermeasures, identify assets, present, evaluate"], 1,
         "Steps 5–8: assess, evaluate risks, develop recommendations, present recommendations.", "Ch6 · RA plan"),
        ("Port scanning and trace routing to detect network topology are threats against the:",
         ["Application", "Host", "Network", "Database"], 2, "They are information-gathering threats against the network.", "Ch3 · Network threats"),
    ],
    "tf": [
        ("Security blueprints are used to identify and design security requirements.", True, "That is one purpose of security blueprints.", "Ch1 · Governance"),
        ("Both quantitative and qualitative risk analysis are often required to get a full picture.", True, "Each has unique capabilities.", "Ch2 · Analysis"),
        ("OCTAVE addresses technological risks rather than organizational risks.", False, "OCTAVE focuses on organizational risks and does not address technological risks.", "Ch3 · OCTAVE"),
        ("In attack trees, special notation is needed to show AND relationships.", True, "Children are ORed by default; AND needs special notation.", "Ch3 · Attack trees"),
        ("Asset values are assigned during asset identification, before the inventory is complete.", False, "Assets are identified without pre-judging value; values come later.", "Ch4 · Inventory"),
        ("A likelihood value of zero is used for vulnerabilities that are very unlikely.", False, "Zero is not used; zero-likelihood vulnerabilities are removed.", "Ch5 · Likelihood"),
        ("Scope creep wastes time and resources by evaluating assets outside the RA boundary.", True, "That is the definition in Chapter 6.", "Ch6 · Assets"),
        ("The POAM is submitted in phase one for top management to approve the ranked risks.", False, "Phase one submits the ranked risk list; the POAM is phase two.", "Ch6 · Presenting results"),
    ],
    "fill": [
        ("________ IT is a governance framework used to create business value from IT investments.", "Val", ["val"], "Val IT.", "Ch1 · Frameworks"),
        ("The step of risk management that creates DRP, BCP and IRP plans is risk ________.", "control", ["control", "response"], "Step 4: risk control (risk response planning).", "Ch2 · Steps"),
        ("The D in STRIDE stands for denial of ________.", "service", ["service"], "STRIDE: Denial of service.", "Ch3 · STRIDE"),
        ("Asset classification categories must be comprehensive and mutually ________.", "exclusive", ["exclusive"], "Comprehensive and mutually exclusive.", "Ch4 · Classification"),
        ("The ________ risk worksheet is the final summary of the risk assessment.", "ranked", ["ranked"], "The ranked (vulnerability) risk worksheet.", "Ch5 · Results"),
        ("Penetration testing is used in an ________ assessment.", "exploit", ["exploit"], "Exploit assessment = penetration testing.", "Ch6 · Vulnerabilities"),
    ],
    "calc": [
        ("A laptop worth $1,800 is stolen twice a year. Locks costing $400 a year would reduce thefts to once a year. What are the annual savings with the locks?", "1,400", ["1400", "1,400"],
         "ALE before = 1,800 × 2 = 3,600; ALE after = 1,800; savings = 3,600 − 1,800 − 400 = 1,400.", "Ch5 · Quantitative"),
        ("Asset value 60, likelihood 0.5, 20% already controlled, data 90% accurate. Using the risk determination formula, what is the risk?", "27", ["27"],
         "Base = 30; − 20% (6) + 10% (3) = 27.", "Ch5 · Risk determination"),
        ("A threat scores Damage 2, Reproducibility 3, Exploitability 3, Affected users 2, Discoverability 1. What is the DREAD total?", "11", ["11"], "2 + 3 + 3 + 2 + 1 = 11.", "Ch3 · DREAD"),
        ("Weights: cost 20, revenue 50, public image 30. An asset scores 0.5, 0.6 and 0.9. What is its weighted score?", "67", ["67"], "10 + 30 + 27 = 67.", "Ch4 · Weighted analysis"),
        ("A payment server earns $4,000 per hour. Recovery needs a $1,000 part and 5 hours of downtime. What is the recovery value?", "21,000", ["21000", "21,000"], "5 × 4,000 = 20,000 + 1,000 = 21,000.", "Ch6 · Recovery value"),
    ],
    "match": [
        ("Match each concept to its chapter topic.", "Ch1–6 · Concepts", [
            ("Three levels of planning", "Strategic, tactical, operational"),
            ("Mitigation options", "Accept, reduce, transfer, avoid"),
            ("DREAD", "Scoring threats to prioritize them"),
            ("TVA worksheet", "Threats, vulnerabilities and assets combined"),
            ("POAM", "Plan Of Actions and Milestones"),
        ]),
        ("Match each quantitative or qualitative term to its meaning.", "Ch2 and Ch5 · Terms", [
            ("SLE", "Asset value multiplied by exposure factor"),
            ("ARO", "Expected incidents per year"),
            ("ALE", "SLE multiplied by ARO"),
            ("Impact", "Magnitude of loss if a risk occurs"),
            ("Likelihood", "Probability a vulnerability is successfully attacked"),
        ]),
    ],
    "short": [
        ("Trace a complete risk management effort from asset identification to presenting results, naming the key deliverable at each stage.",
         ["inventory", "tva", "assessment", "ranked", "recommendations", "poam"],
         "Identify assets (asset inventory) without pre-judging value, classify them (asset classification worksheet), and value and rank them (weighted criteria analysis worksheet). Identify threats and vulnerabilities per asset to build the threat–vulnerability matrix and the TVA worksheet. Perform a quantitative (SLE, ARO, ALE) or qualitative (probability × impact) risk assessment and summarize it in the ranked vulnerability risk worksheet. Develop mitigating recommendations with cost-benefit analysis, present the ranked risks to top management, and implement approved items through a POAM.",
         "Ch4–6 · Lifecycle"),
        ("Scenario: An online store's customer database is worth $200,000. A breach would expose 30% of its value and happens about once every two years. A database activity monitoring tool costs $12,000 a year and would cut the rate to once every ten years. Should the store buy it? Show SLE, ARO, ALE and savings.",
         ["60000", "0.5", "30000", "6000", "12000", "savings"],
         "SLE = 200,000 × 0.30 = $60,000. ARO before = 0.5, so ALE before = $30,000. ARO after = 0.1, so ALE after = $6,000. Savings = 30,000 − 6,000 − 12,000 = $12,000. The savings are positive, so the tool is cost-justified.",
         "Ch2 and Ch5 · Quantitative"),
        ("Using STRIDE, identify one threat in each category for an online banking login page and suggest a control for two of them.",
         ["spoofing", "tampering", "repudiation", "disclosure", "denial", "elevation"],
         "Spoofing: an attacker logs in with stolen credentials (control: multi-factor authentication). Tampering: changing transfer amounts in transit (control: TLS and integrity checks). Repudiation: a user denies making a transfer (audit logging). Information disclosure: error messages reveal account data. Denial of service: flooding the login page. Elevation of privilege: a normal user gains admin functions.",
         "Ch3 · STRIDE"),
        ("Explain why the risk assessment team should be independent, and how the scope should relate to the management structure.",
         ["conflict", "independent", "input", "scope", "single", "owner"],
         "The RA team should not be the people responsible for correcting deficiencies, to avoid a conflict of interest, although their input is important. The scope should be kept within the ownership of a single entity and not cross management lines, so every recommendation has one clear decision maker and the RA can be acted on.",
         "Ch5–6 · Team and scope"),
    ],
}


# --------------------------------------------------------------------------- past papers
# Transcribed from the marked exam papers. Options keep the printed A/B/C/D order.

PAST_QUIZ_1 = {
    "keep_order": True,
    "mcq": [
        ("If different user groups with different security access levels need to access the same information, which of the following actions should management take?",
         ["Require specific written approval each time an individual needs to access the information.",
          "Increase the security controls on the information.",
          "Decrease the security level on the information to ensure accessibility and usability of the information.",
          "Decrease the classification label on the information."], 1,
         "Raise the controls, never lower the classification. Weakening the label or the security level to make sharing easier exposes the information to everyone below that level; written approval for every access is unworkable.",
         "Q1 · Classification"),
        ("The security functionality defines the expected activities of a security mechanism, and assurance defines:",
         ["The confidence of the security the mechanism is providing.",
          "The data classification after the security mechanism has been implemented.",
          "The controls the security mechanism will enforce.",
          "The cost/benefit relationship."], 0,
         "Functionality is what the mechanism does; assurance is how much confidence you have that it does it correctly and consistently.",
         "Q2 · Functionality and assurance"),
        ("Which of the following is not a management role in the process of implementing and maintaining security?",
         ["Support", "Defining purpose and scope", "Delegating responsibility", "Performing risk analysis"], 3,
         "Management supports the programme, sets its purpose and scope, and delegates responsibility. Carrying out the risk analysis itself is the security team's work, not a management role.",
         "Q3 · Management roles"),
        ("What are security policies?",
         ["Step-by-step directions on how to accomplish security tasks.",
          "Broad, high-level statements from the management.",
          "Detailed documents explaining how security incidents should be handled.",
          "General guidelines used to accomplish a specific security level."], 1,
         "Policies are broad, high-level management statements of intent. Step-by-step directions are procedures, and general recommendations are guidelines.",
         "Q4 · Policy"),
        ("Who has the primary responsibility of determining the classification level for information?",
         ["The owner", "The user", "The functional manager", "Senior management"], 0,
         "The data owner classifies the information. Custodians protect it at that level and users follow the handling rules.",
         "Q5 · Data owner"),
        ("Which factor is the most important item when it comes to ensuring security is successful in an organization?",
         ["Security awareness by all employees",
          "Effective controls and implementation methods",
          "Senior management support",
          "Updated and relevant security policies and procedures"], 2,
         "Without senior management support there is no budget, no authority and no enforcement, so awareness, controls and policies never take hold.",
         "Q6 · Governance"),
        ("Which is the best framework that helps organizations meet business challenges in regulatory compliance, risk management and aligning IT strategy with organisational goals?",
         ["ISO 27001", "Risk IT", "COBIT", "Val IT"], 2,
         "COBIT is the IT governance model covering compliance, risk and alignment of IT with business goals; Risk IT covers IT risk only and Val IT covers value from IT investments. Note: the marker's key on your paper points to Risk IT, so check this one with your instructor.",
         "Q7 · Frameworks"),
        ("Who should measure the effectiveness of Information System security related controls in an organization?",
         ["The local security specialist", "The systems auditor", "The central security manager", "The business manager"], 1,
         "Measuring control effectiveness needs independence from the people who run the controls, which is the systems auditor's role.",
         "Q8 · Assurance"),
        ("What would BEST define risk management?",
         ["The process of transferring risk", "The process of assessing the risks",
          "The process of eliminating the risk", "The process of reducing risk to an acceptable level"], 3,
         "Risk can never be eliminated. Risk management reduces it to a level the organization accepts; transfer and assessment are only parts of that process.",
         "Q9 · Risk management"),
        ("Making sure that only those who are supposed to access the data can access it is which of the following?",
         ["Confidentiality", "Availability", "Integrity", "Capability"], 0,
         "Confidentiality restricts access to authorised people. Integrity is about accuracy, availability is about access when needed.",
         "Q10 · CIA triad"),
    ],
}

PAST_QUIZ_2 = {
    "keep_order": True,
    "mcq": [
        ("Who should be involved in Security Risk Management activities? Choose the best answer.",
         ["Only Security Project Team", "Only Project Manager", "As many as practical", "All stakeholders except clients"], 2,
         "Risk management needs as many perspectives as is practical: each group sees risks the others miss. Clients are stakeholders too, so excluding them loses information.",
         "Q1 · Participation"),
        ("When should risk identification be performed? (select the best answer)",
         ["During Concept Phase", "During Development Phase", "During Implementation Phase",
          "Risk identification should be performed on a regular basis throughout the project"], 3,
         "Identification starts early but is repeated throughout: new risks appear as the project changes, so a one-off pass at the concept phase is not enough.",
         "Q2 · Timing"),
        ("An example of risk mitigation is:",
         ["Using proven technology in the development of a product to lessen the probability that the product will not work",
          "Accepting a lower profit if costs overrun", "Eliminating the cause of a risk", "None of the above"], 0,
         "Mitigation (reduction) lowers the probability or impact while still doing the activity. Accepting lower profit is acceptance, and eliminating the cause is avoidance.",
         "Q3 · Mitigation options"),
        ("A process that is not part of Security Risk Management is:",
         ["Identification", "Security maintenance", "Security Policy", "Monitoring and Control"], 1,
         "Security maintenance is an operational activity. Risk management covers identification, policy and the monitoring and control of risks.",
         "Q4 · Risk management processes"),
        ("How is an \"attack\" represented?",
         ["Asset + Threat + Vulnerability", "Asset + Threat", "Motive (goal) + method", "Motive (goal) + method + vulnerability"], 3,
         "An attack needs someone who wants something (motive), a way to do it (method) and a weakness to use (vulnerability). Asset + threat + vulnerability is how risk is represented, not an attack.",
         "Q5 · Attack"),
    ],
    "short": [
        ("List 2 types of Cybersecurity Framework and explain. [0.5 Marks]",
         ["risk it", "val it", "cobit", "risk", "value", "governance"],
         "Any two of the ISACA frameworks, explained. Risk IT: an end-to-end view of all risks arising from the use of IT, covering how to be aware of risks and manage them before, during and after they happen. Val IT: a governance framework for creating business value from IT investments. COBIT: the IT governance model that helps deliver value from IT and understand and manage the risks that come with it.",
         "Q6 · Frameworks"),
        ("Why do executives and IT/security need to have knowledge connections and good relations and communication between both parties? [0.5 Marks]",
         ["business", "risk", "communicat", "gap", "decision", "priorit", "value", "goals"],
         "Cyber risk is a business risk, so it cannot be managed inside an IT silo. Executives control budget and priorities but often cannot interpret a security report, while IT understands the risks but not the business goals. Bridging that gap lets risks be expressed in business terms, funded appropriately, and aligned with the organization's objectives, so security supports value creation instead of blocking it.",
         "Q7 · Business alignment"),
        ("Renee is designing the short-term security plan for her organization and has a one- to six-month planning horizon. What type of plan is she developing? [0.5 Marks]",
         ["operational"],
         "An operational plan. The three levels of security planning are strategic (long range, around five years), tactical (mid term, about one year) and operational (short term, roughly one to six months, covering day-to-day tasks).",
         "Q8 · Levels of planning"),
        ("Explain in detail how a \"risk\" is represented. [1 Mark]",
         ["threat", "vulnerabilit", "asset", "loss", "probability", "impact"],
         "Risk is the possibility that a threat exploits a vulnerability in an asset and causes loss or damage. It is represented as Threat x Vulnerability x Asset value, so risk exists only when all three are present: something valuable, a weakness in it, and someone or something able to exploit that weakness. Its size is judged by the probability of that happening and the impact if it does.",
         "Q9 · Risk representation"),
    ],
}

PAST_MAJOR = {
    "keep_order": True,
    "mcq": [
        ("What does \"residual risk\" mean?",
         ["The security risk that remains after controls have been implemented",
          "Weakness of an asset which can be exploited by a threat",
          "Risk that remains after risk assessment has been performed",
          "A security risk intrinsic to an asset being audited, where no mitigation has taken place"], 0,
         "Residual risk is what is left after the controls are in place. The weakness itself is a vulnerability, and the risk before any mitigation is inherent risk.",
         "A1 · Residual risk"),
        ("This category of control can include the logical mechanisms used to control access and authenticate users.",
         ["Administrative", "Clerical", "Technical", "Physical"], 2,
         "Technical (logical) controls are implemented in software and hardware: authentication, access control lists, encryption. Administrative controls are policies and procedures; physical controls are locks and guards.",
         "A2 · Control categories"),
        ("Which of the following formulas represents total risk?",
         ["Risk X Vulnerability X Asset value = Total risk",
          "Threat X Vulnerability X Asset value = Total risk",
          "Risk X Value/Countermeasure = Total risk",
          "Threat - Vulnerability/Asset value = Total risk"], 1,
         "Total risk = Threat x Vulnerability x Asset value. Residual risk is that total minus the effect of the controls in place.",
         "A3 · Total risk"),
        ("Which best describes a quantitative risk analysis?",
         ["A scenario-based analysis to research different security threats",
          "A method used to apply severity levels to potential loss, probability of loss, and risks",
          "A method that assigns monetary values to components in the risk assessment",
          "A method that is based on gut feelings and opinions"], 2,
         "Quantitative analysis puts money values on assets, losses and controls (SLE, ARO, ALE). Applying severity levels or scenarios without numbers is qualitative.",
         "A4 · Quantitative analysis"),
        ("When is it acceptable to not take action on an identified risk?",
         ["Never. Good security addresses and reduces all risks.",
          "When political issues prevent this type of risk from being addressed.",
          "When the necessary countermeasure is complex.",
          "When the cost of the countermeasure outweighs the value of the asset and potential loss."], 3,
         "Accepting a risk is justified when the control costs more than the loss it prevents. Complexity or politics are not valid reasons, and no organization can remove every risk.",
         "A5 · Risk acceptance"),
        ("SQL Injection is a ________ type of threat.",
         ["Network", "Host", "Application", "Management"], 2,
         "SQL injection abuses input handling in the application itself, so it is an application-level threat.",
         "A6 · Threat types"),
        ("An internal IS auditor recommends that incoming accounts payable payment files be encrypted. Which type of control is the auditor recommending?",
         ["Corrective", "Detective", "Preventive", "Directive"], 2,
         "Encryption stops disclosure before it happens, so it is preventive. Detective controls find incidents, corrective controls fix them and directive controls instruct people.",
         "A7 · Control types"),
        ("Which of the following is not a type of threat?",
         ["Network", "Host", "Application", "Management"], 3,
         "Threats are classified against the network, the host and the application. Management is a category of control, not a threat.",
         "A8 · Threat types"),
        ("What is the prime directive of Risk Management?",
         ["Reduce all risks regardless of cost", "Reduce the risk to a tolerable level",
          "Transfer any risk to external third parties", "Prosecute any employees that are violating published security policies"], 1,
         "The aim is to bring risk down to a tolerable (acceptable) level at a sensible cost, not to remove every risk.",
         "A9 · Prime directive"),
        ("If different user groups with different security access levels need to access the same information, which of the following actions should management take?",
         ["Decrease the security level on the information to ensure accessibility and usability of the information.",
          "Require specific written approval each time an individual needs to access the information.",
          "Increase the security controls on the information.",
          "Decrease the classification label on the information."], 2,
         "Strengthen the controls so the information can be shared safely. Lowering the level or the label exposes it, and per-access written approval does not scale.",
         "A10 · Classification"),
    ],
    "short": [
        ("Identify 1 (ONE) BEST technique to assist security and financial analysts in determining if a security control is cost effective to mitigate a vulnerability. [1 Mark]",
         ["cost", "benefit"],
         "Cost/benefit analysis. Compare the loss the control prevents with what the control costs: value of control = (ALE before control) - (ALE after control) - (annual cost of control). A positive result means the control is worth buying.",
         "B1 · Cost/benefit analysis"),
        ("He is in charge of the data in a certain data domain (data classification). He must guarantee that the information inside that domain is correctly maintained across various platforms and business processes. Identify who has the primary responsibility of determining the classification level for information. [1 Mark]",
         ["owner", "data owner"],
         "The data owner. The owner classifies the information and decides who may access it; the custodian maintains and protects it at that classification.",
         "B2 · Data owner"),
        ("Explain Threat amplifiers and Threat inhibitors with an example for each. [1 Mark]",
         ["amplifier", "inhibitor", "peer pressure", "fear", "difficulty", "gain", "detection", "probability"],
         "Threat amplifiers raise the likelihood that an attack is attempted: peer pressure, fame, personal gain, political motives. Example: a hacker group praising an attack encourages copycats. Threat inhibitors lower it: fear of capture, fear of failure, difficulty of the attack, cost of participation, level of sensitivity. Example: strong monitoring makes detection likely, so the attacker chooses another target.",
         "B3 · Threat amplifiers and inhibitors"),
        ("Explain Decision Tree Analysis and identify the risk assessment technique that applies to it. [2 Marks]",
         ["decision", "tree", "branch", "outcome", "probability", "evaluation", "path"],
         "A decision tree maps each decision and its possible outcomes as branches, with the probability and the cost or benefit of each path, so the expected value of each option can be compared and the best one chosen. Each node asks a yes/no question and leads to the next step until an acceptable option is reached. It belongs to risk evaluation: you are evaluating options against whether the resulting risk is acceptable.",
         "B4 · Decision tree analysis"),
        ("You are a security officer in company XYZ. Your manager requests you to prepare the asset identification documentation. Write the name of the process/activity of asset identification. [0.5 Marks]",
         ["asset identification", "inventory"],
         "Asset identification and inventory: listing every information asset the organization holds before it can be valued, classified and protected. (Asset valuation is the step that follows, once the inventory exists.)",
         "C1a · Asset identification"),
        ("List 2 (TWO) information assets with 2 (TWO) attributes of each. [1 Mark]",
         ["name", "owner", "classification", "location", "value", "serial", "version", "type"],
         "For example: a customer database, with attributes owner (marketing manager) and classification (confidential); and a payroll application server, with attributes IP address/location (data centre rack 4) and asset value (critical). Recognised attributes include name, ID number, owner, classification, location, serial or version number, manufacturer and value.",
         "C1b · Asset attributes"),
        ("Your company is developing a modern application that will run as an Azure App Service web app. You plan to perform threat modelling to identify potential security issues by using the Microsoft Threat Modelling Tool. Write the name of the threat modelling method and identify 2 (TWO) important requirements needed for the process. [2 Marks]",
         ["stride", "spoofing", "tampering", "data flow", "diagram", "asset", "architecture", "component"],
         "The Microsoft Threat Modelling Tool uses STRIDE (Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege). Two requirements for the process: a data flow diagram or architecture of the application showing components, trust boundaries and data flows; and an inventory of the assets and entry points to be protected. The output is a list of threats per component with the controls that address them.",
         "C2 · STRIDE"),
        ("Write 1 (ONE) condition when you should apply Risk Avoidance. [1 Mark]",
         ["too high", "unacceptable", "stop", "not proceed", "alternative", "cost", "outweigh"],
         "Apply avoidance when the risk is so high that no acceptable control can bring it down, and the loss would outweigh the benefit of the activity. You then stop or do not start that activity, or choose an alternative approach that does not carry the risk.",
         "C3a · Risk avoidance"),
        ("Identify 2 (TWO) steps you need to do after finishing the risk assessment task. [2 Marks]",
         ["risk control", "review", "monitor", "report", "recommend", "document", "treat"],
         "After assessment comes risk control (treatment): select and implement the countermeasures for the prioritised risks. Then risk review and monitoring: document and report the results to management, and re-check the risks periodically so new or changed risks are caught. Presenting the ranked findings and recommendations to management is part of that handover.",
         "C3b · After the assessment"),
    ],
    "calc": [
        ("Company X sells laptops online and makes an average profit of $20,000 per week. A typical DoS attack lowers sales by 40%. What is the SLE? [part of 3.5 Marks]",
         "8,000", ["8000", "8,000"],
         "SLE = asset value x exposure factor = 20,000 x 0.40 = $8,000 lost per attack.",
         "C4a · SLE"),
        ("Company X suffers four DoS attacks on average every 6 months. What is the ARO (attacks per year)?",
         "8", ["8"],
         "ARO is per year: 4 attacks per 6 months = 8 attacks per year.",
         "C4a · ARO"),
        ("Using SLE = $8,000 and ARO = 8, what is the ALE before the countermeasure?",
         "64,000", ["64000", "64,000"],
         "ALE = SLE x ARO = 8,000 x 8 = $64,000 per year.",
         "C4a · ALE before"),
        ("The mitigation service reduces the attacks to 80% of the original number. What is the ALE after the countermeasure?",
         "51,200", ["51200", "51,200"],
         "ARO after = 8 x 0.8 = 6.4, so ALE after = 8,000 x 6.4 = $51,200. Note the wording: the marked key treats \"reduced 80%\" as reduced to 80% of the attacks. If it meant reduced by 80%, ARO would be 1.6 and ALE after $12,800.",
         "C4b · ALE after"),
        ("The service costs $1,000 per month plus $1,500 one-time installation. What is the value of the control (cost benefit analysis) for the first year?",
         "-700", ["-700", "- 700", "700"],
         "Annual cost = 1,000 x 12 + 1,500 = $13,500. Value = ALE before - ALE after - cost = 64,000 - 51,200 - 13,500 = -$700. The result is negative, so on these figures the service is not a good investment and the company should reconsider.",
         "C4c · Cost benefit analysis"),
    ],
}

EXAMS = [
    {"slug": "quiz-1-practice-exam", "label": "Quiz 1 Practice Exam", "short": "Quiz 1", "scope": "Chapters 1–2",
     "heading": "Quiz 1 practice exam (Chapters 1–2)", "quiz": QUIZ_1},
    {"slug": "major-exam-practice", "label": "Major Exam Practice", "short": "Major Exam", "scope": "Chapters 1–6",
     "heading": "Major exam practice (Chapters 1–6)", "quiz": MAJOR},
    {"slug": "past-term-222-quiz-1", "label": "Term 222 · Quiz 1", "short": "Term 222 Quiz 1",
     "scope": "Past paper", "heading": "Past paper · Term 222 · Quiz 1", "quiz": PAST_QUIZ_1},
    {"slug": "past-term-unknown-quiz-2", "label": "Term unknown · Quiz 2", "short": "Quiz 2",
     "scope": "Past paper", "heading": "Past paper · Term unknown · Quiz 2", "quiz": PAST_QUIZ_2},
    {"slug": "past-term-unknown-major-exam", "label": "Term unknown · Major Exam", "short": "Major Exam",
     "scope": "Past paper", "heading": "Past paper · Term unknown · Major Examination", "quiz": PAST_MAJOR},
]
